---
title: "Teaching"
description: |
  My teaching experience has been developed at undergraduate and postgraduate levels in courses on social network analysis applied to economics, labour economics, economic development, research methodology in economics and data analysis using [*R*](<https://www.r-project.org/>){target="_blank"}.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Postgraduate

- Networks and innovation systems. Theoretical and methodological foundations - PhD in Economics of Innovation - UNSAM 
  - From 2024 to the present
- Social Network Analysis - Master in Economics - FCEA - UdelaR.
  - From 2018 to present
  - There is an online version of the course available at this [link](<https://sergio-palomeque.github.io/ARS_Course/>){target="_blank"}.
- Topics in Labour Economics - Master in Economics - FCEA - UdelaR.
  - From 2017 to 2019.

# Undergraduate

- Databases and Statistical Packages - Bachelor's Degree in Economics - FCEA - UdelaR.
  - Between 2017 and 2024, I was part of the staff of this course, where I was responsible for the module on statistical software [*R*](<https://www.r-project.org/>){target="_blank"}.
- Introduction to Research Methodology - Bachelor's Degree in Economics - FCEA - UdelaR.
  - Between 2022 and 2024 I conducted workshops on research methodology, guiding teams in the development of a research project.
- Development and Welfare - Bachelor's Degree in Economics - FCEA - UdelaR.
  - Between 2021 and 2022 I participated in this course based on some chapters of [The Economy](<https://www.core-econ.org/the-economy/en/>){target="_blank"}
  
# Workshops

- Using patent data for collaboration network analysis. An application with USTPO data in PatentsView
  - Together with Dr. Pablo Galaso, we taught this [workshop](https://www.insna.org/using-patent-data-for-collaboration-network-analysis-an-application-with-ustpo-data-in-patentsview){target="_blank"} at Sunbelt Congress 2023 and 2024. This is the annual meeting of the International Network for Social Network Analysis, one of the world's two most important social network analysis communities.